config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'

  resource :games do
    collection do
      get :history
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  belongs_to :opponent, class_name: 'User', foreign_key: 'opponent_id'

  validates_presence_of :user_id, :opponent_id, :date_played, :user_score,
    :opponent_score
  before_save :validate_score
  after_save :update_ranking


  def score
    "#{user_score} - #{opponent_score}"
  end

  def result
    won? ? "W" : "L"
  end

  def won?
    user_score > opponent_score
  end

  private

  def validate_score
    diff = user_score - opponent_score
    return true  if (user_score == 21 || opponent_score == 21) && diff >= 2
    errors.add(:base, "Invalid score. They are games to 21. Each game needs to be won by a two point margin.")
    false
  end

  def update_ranking
    return unless won?
    importance = opponent.score > user.score ? 1.5 : 1.0
    user.score += user_score * importance
    user.save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable
  has_many :games

  attr_accessor :rank

  def oponents_to_select
    User.where("id != ?", self.id).all.map{ |user| [user.email, user.id] }
  end

  def self.leaderborad
    users =  User.all.order("score DESC")
    rank = 0
    users.each { |user| rank += 1; user.rank = rank }
    users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id

    if @game.save
      flash[:notice] = "Game was created successfully."
      redirect_to root_path
    else
      flash[:error] = "Game was not crated due to the next errors:"
      render :new
    end
  end

  def history
    @games = current_user.games.all
  end

  def game_params
    params.require(:game).permit(:opponent_id, :date_played, :user_score, :opponent_score)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.leaderborad
  end

  def history
  end

  def log
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_game.html.erb
<tr>
 <td><%= game.date_played %></td>
 <td><%= game.opponent.email %></td>
 <td><%= game.score %></td>
 <td><%= game.result %></td>
</tr>

app/views/games/history.html.erb
<h1 class='page-header'>History</h1>


<p class="text-info">
  History of games for user <%= current_user.email %>
</p>

<table class="table">
  <tr>
    <td>Date</td>
    <td>Opponent</td>
    <td>Score</td>
    <td>Result</td>
  </tr>
  <%= render partial: 'game', collection: @games %>
</table>

app/views/games/new.html.erb
<h1 class='page-header'>Log Game</h1>

<% if flash[:error].present? %>
  <div class="alert alert-danger" role="danger">
    <%= flash[:error].html_safe %><br/>
    <%= @game.errors.full_messages.join('<br />').html_safe %>
  </div>
<% end %>

<%= form_for(@game) do |f| %>
  <div class="form-group">
    <label for="date_played">Date played:</label>
    <%= f.date_select :date_played %>
  </div>
  <div class="form-group">
    <label for="opponent_id">Opponent:</label>
    <%= f.select :opponent_id, current_user.oponents_to_select %>
  </div>

  <div class="form-group">
    <label for="user_score">Your score:</label>
    <%= f.text_field :user_score %>
  </div>
  <div class="form-group">
    <label for="opponent_score">Their score:</label>
    <%= f.text_field :opponent_score %>
  </div>

  <button type="submit" class="btn btn-default">Submit</button>
<% end %>

app/views/home/_user.html.erb
<tr>
 <td><%= user.rank %></td>
 <td><%= user.email %></td>
 <td><%= user.score %></td>
 <td><%= user.games.size %></td>
</tr>

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<% if flash[:notice].present? %>
  <div class="alert alert-info" role="info">
    <%= flash[:notice] %>
  </div>
<% end %>

<table class="table">
  <tr>
    <td>Rank</td>
    <td>Name</td>
    <td>Score</td>
    <td>Games Played</td>
  </tr>
  <%= render partial: 'user', collection: @users %>
</table>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', new_games_path, class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "History", history_games_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>